DROP SCHEMA IF EXISTS inventory_reservation CASCADE;
CREATE SCHEMA inventory_reservation;

SET search_path = inventory_reservation, public;

CREATE TABLE products (
    product_id BIGINT PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE
);

CREATE TABLE warehouses (
    warehouse_id BIGINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE inventory (
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(warehouse_id),
    on_hand INTEGER NOT NULL CHECK (on_hand >= 0),
    reserved INTEGER NOT NULL DEFAULT 0 CHECK (reserved >= 0),
    PRIMARY KEY (product_id, warehouse_id),
    CHECK (reserved <= on_hand)
);

CREATE TABLE reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    status TEXT NOT NULL CHECK (status IN ('active', 'released', 'confirmed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    FOREIGN KEY (product_id, warehouse_id)
        REFERENCES inventory(product_id, warehouse_id)
);

CREATE INDEX reservations_active_inventory_idx
    ON reservations(product_id, warehouse_id)
    WHERE status = 'active';

CREATE TABLE operation_results (
    operation_id TEXT PRIMARY KEY,
    operation_name TEXT NOT NULL,
    success BOOLEAN NOT NULL,
    code TEXT NOT NULL,
    reservation_id BIGINT,
    committed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
